version: '3.6'
services:
  ruby-maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ruby-maze-runner
      target: ruby-maze-runner
    environment:
      NETWORK_NAME: "${BUILDKITE_JOB_ID:-ruby-maze-runner}-${RUBY_TEST_VERSION:-local}"
      BUILDKITE_JOB_ID:
      RAILS_VERSION:
      SIDEKIQ_VERSION:
      RUBY_TEST_VERSION:
      VERBOSE:
      DEBUG:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ruby-unit-tests:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ruby-unit-tests
      args:
        - RUBY_TEST_VERSION
        - GEMSETS=${GEMSETS:-test}
        - BUNDLE_VERSION=${BUNDLE_VERSION:-1.12.0}

  jruby-unit-tests:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.jruby-unit-tests
      args:
        - GEMSETS=${GEMSETS:-test}
        - BUNDLE_VERSION=${BUNDLE_VERSION:-1.12.0}

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-ruby-maze-runner}-${RUBY_TEST_VERSION:-local}