steps:
  - label: ':docker: Build CI image'
    plugins:
      - docker-compose#v2.6.0:
          build: ruby-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/ruby
          cache-from: ruby-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/ruby:ci-ruby${BRANCH_NAME}
      # - docker-compose#v2.6.0:
      #     push:
      #       - ci: ruby-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/ruby:ci-ruby${BRANCH_NAME}

  - wait

  - label: ':ruby: Ruby 2.6 unit tests'
    plugins:
      docker-compose#v2.6.0:
        run: ruby-unit-tests
        use-aliases: true
    env:
      RUBY_TEST_VERSION: "2.6"

  - label: ':ruby: Ruby 2.6 plain tests'
    plugins:
      docker-compose#v2.6.0:
        run: ruby-maze-runner
        use-aliases: true
    env:
      RUBY_TEST_VERSION: "2.6"
      VERBOSE: true
    command: features/plain_features/ --tags "not @wip"

  - label: ':ruby: :rails: Rails 6 Ruby 2.6 tests'
    plugins:
      docker-compose#v2.6.0:
        run: ruby-maze-runner
        use-aliases: true
    env:
      RUBY_TEST_VERSION: "2.6"
      RAILS_VERSION: "6"
      VERBOSE: true
    command: features/rails_features/ --tags "@rails6 and not @wip"

  - block: "Trigger full test suite"

  - label: ':ruby: Ruby 1.9.3 plain tests'
    plugins:
      docker-compose#v2.6.0:
        run: ruby-maze-runner
        use-aliases: true
    env:
      RUBY_TEST_VERSION: "1.9.3"
      VERBOSE: true
    command: features/plain_features --tags "not @wip"

  - label: ':ruby: Ruby 2.0 plain tests'
    plugins:
      docker-compose#v2.6.0:
        run: ruby-maze-runner
        use-aliases: true
    env:
      RUBY_TEST_VERSION: "2.0"
      VERBOSE: true
    command: features/plain_features --tags "not @wip"

  - label: ':ruby: Ruby 2.1 plain tests'
    plugins:
      docker-compose#v2.6.0:
        run: ruby-maze-runner
        use-aliases: true
    env:
      RUBY_TEST_VERSION: "2.1"
      VERBOSE: true
    command: features/plain_features --tags "not @wip"

  - label: ':ruby: Ruby 2.2 plain tests'
    plugins:
      docker-compose#v2.6.0:
        run: ruby-maze-runner
        use-aliases: true
    env:
      RUBY_TEST_VERSION: "2.2"
      VERBOSE: true
    command: features/plain_features --tags "not @wip"

  - label: ':ruby: Ruby 2.3 plain tests'
    plugins:
      docker-compose#v2.6.0:
        run: ruby-maze-runner
        use-aliases: true
    env:
      RUBY_TEST_VERSION: "2.3"
      VERBOSE: true
    command: features/plain_features --tags "not @wip"

  - label: ':ruby: Ruby 2.4 plain tests'
    plugins:
      docker-compose#v2.6.0:
        run: ruby-maze-runner
        use-aliases: true
    env:
      RUBY_TEST_VERSION: "2.4"
      VERBOSE: true
    command: features/plain_features --tags "not @wip"

  - label: ':ruby: Ruby 2.5 plain tests'
    plugins:
      docker-compose#v2.6.0:
        run: ruby-maze-runner
        use-aliases: true
    env:
      RUBY_TEST_VERSION: "2.5"
      VERBOSE: true
    command: features/plain_features --tags "not @wip"